"""update lyrics table

Revision ID: 8ce1cde0e53e
Revises: c7533cbbb762
Create Date: 2026-03-05 11:52:29.231722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce1cde0e53e'
down_revision: Union[str, Sequence[str], None] = 'c7533cbbb762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lyrics', sa.Column('client_uid', sa.String(length=36), nullable=True))
    op.add_column('lyrics', sa.Column('source', sa.String(length=20), server_default='web', nullable=False))
    op.add_column('lyrics', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_lyrics_client_uid'), 'lyrics', ['client_uid'], unique=False)
    op.create_unique_constraint('uq_lyrics_user_client_uid', 'lyrics', ['user_id', 'client_uid'])
    op.drop_constraint(op.f('lyrics_user_id_fkey'), 'lyrics', type_='foreignkey')
    op.create_foreign_key(None, 'lyrics', 'users', ['user_id'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lyrics', type_='foreignkey')
    op.create_foreign_key(op.f('lyrics_user_id_fkey'), 'lyrics', 'users', ['user_id'], ['uid'])
    op.drop_constraint('uq_lyrics_user_client_uid', 'lyrics', type_='unique')
    op.drop_index(op.f('ix_lyrics_client_uid'), table_name='lyrics')
    op.drop_column('lyrics', 'deleted_at')
    op.drop_column('lyrics', 'source')
    op.drop_column('lyrics', 'client_uid')
    # ### end Alembic commands ###
