"""modify scratchpad

Revision ID: 0dd78518cb3a
Revises: 0e08e0feb93a
Create Date: 2026-02-07 12:35:53.844929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd78518cb3a'
down_revision: Union[str, Sequence[str], None] = '0e08e0feb93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_scratchpad_user_id'), 'scratchpad', ['user_id'], unique=False)
    op.drop_constraint(op.f('scratchpad_ibfk_1'), 'scratchpad', type_='foreignkey')
    op.create_foreign_key(None, 'scratchpad', 'users', ['user_id'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scratchpad', type_='foreignkey')
    op.create_foreign_key(op.f('scratchpad_ibfk_1'), 'scratchpad', 'users', ['user_id'], ['uid'])
    op.drop_index(op.f('ix_scratchpad_user_id'), table_name='scratchpad')
    # ### end Alembic commands ###
