"""initial schema

Revision ID: 123f4a0d581c
Revises: 
Create Date: 2026-02-27 20:35:24.922937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '123f4a0d581c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_name', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_name')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artist_name', sa.String(length=150), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('artist_name'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lyrics',
    sa.Column('song_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('song_name', sa.String(length=150), nullable=False),
    sa.Column('song_genre', sa.String(length=100), nullable=False),
    sa.Column('song_lyrics', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_artist', sa.String(length=150), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.Column('song_mood', sa.String(length=100), nullable=True),
    sa.Column('song_album', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('song_id')
    )
    op.create_table('scratchpad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scratchpad_user_id'), 'scratchpad', ['user_id'], unique=False)
    op.create_table('statefold',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('song_name', sa.String(length=150), nullable=True),
    sa.Column('song_genre', sa.String(length=150), nullable=True),
    sa.Column('song_lyrics', sa.Text(), nullable=True),
    sa.Column('song_artist', sa.String(length=150), nullable=True),
    sa.Column('song_mood', sa.String(length=150), nullable=True),
    sa.Column('song_album', sa.String(length=150), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_writing_time', sa.Integer(), nullable=True),
    sa.Column('writing_sessions', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    op.drop_table('statefold')
    op.drop_index(op.f('ix_scratchpad_user_id'), table_name='scratchpad')
    op.drop_table('scratchpad')
    op.drop_table('lyrics')
    op.drop_table('users')
    op.drop_table('admin')
    # ### end Alembic commands ###
