"""add column to stats

Revision ID: 1aa0e2c414d8
Revises: 123f4a0d581c
Create Date: 2026-02-27 22:10:24.419683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa0e2c414d8'
down_revision: Union[str, Sequence[str], None] = '123f4a0d581c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('date_created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats', 'date_created')
    # ### end Alembic commands ###
