"""update scratchpad

Revision ID: 747f2914dacd
Revises: 77cad4f05899
Create Date: 2026-02-07 09:41:17.497184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747f2914dacd'
down_revision: Union[str, Sequence[str], None] = '77cad4f05899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("scratchpad_ibfk_1", "scratchpad", type_="foreignkey")
    op.drop_index("user_id", table_name="scratchpad")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('user_id'), 'scratchpad', ['user_id'], unique=True)
    # ### end Alembic commands ###
