"""add date created at for contacts model

Revision ID: b4d578dbc7f7
Revises: c1fc2bdd303b
Create Date: 2026-04-25 14:51:24.010947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d578dbc7f7'
down_revision: Union[str, Sequence[str], None] = 'c1fc2bdd303b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_messages', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_contact_messages_date_created'), 'contact_messages', ['date_created'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_messages_date_created'), table_name='contact_messages')
    op.drop_column('contact_messages', 'date_created')
    # ### end Alembic commands ###
