"""update states table

Revision ID: c7533cbbb762
Revises: 1aa0e2c414d8
Create Date: 2026-02-27 22:36:54.759693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7533cbbb762'
down_revision: Union[str, Sequence[str], None] = '1aa0e2c414d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'total_writing_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'writing_sessions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('stats_user_id_key'), 'stats', type_='unique')
    op.create_index(op.f('ix_stats_date_created'), 'stats', ['date_created'], unique=False)
    op.create_index(op.f('ix_stats_user_id'), 'stats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_user_id'), table_name='stats')
    op.drop_index(op.f('ix_stats_date_created'), table_name='stats')
    op.create_unique_constraint(op.f('stats_user_id_key'), 'stats', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('stats', 'date_created',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('stats', 'writing_sessions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'total_writing_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
